repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Optional: specify a fixed version using `rev: vX.Y.Z`
    rev: v0.11.8
    hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
