services:
  web:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: backend/Dockerfile

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    # Add environment variables
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/community_bot
      - REDIS_URL=redis://redis:6379/0

    # Add dependencies
    depends_on:
      - db
      - redis

    # env_file:
    #   - .env

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: backend
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=community_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: