[project]
name = "community-engagement"
version = "0.1.0"
description = "yet another try to make something useful"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pre-commit>=4.2.0",
    "ruff>=0.11.8",
    "uvicorn>=0.34.2",
]
